name: Waka Readme

on:
  workflow_dispatch:
  schedule:
  # Runs at 12 AM IST (6:30 PM UTC) every day
  - cron: "30 18 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master 
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          ### meta
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: aditya26062003/aditya26062003 
          
          ### content
          SHOW_TITLE: true 
          SECTION_NAME: waka 
          BLOCKS: -> 
          CODE_LANG: f#
          TIME_RANGE: all_time 
          LANG_COUNT: 4
          SHOW_TIME: false 
          SHOW_TOTAL: false 
          SHOW_MASKED_TIME: false 
          STOP_AT_OTHER: true 
          IGNORED_LANGUAGES: YAML JSON TOML
          ### commit
          COMMIT_MESSAGE: Updated waka-readme graph with new metrics
          TARGET_BRANCH: master
          TARGET_PATH: README.md 
          COMMITTER_NAME: GitHubActionBot 
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: Aditya Singh 
