name: Github Chess Metrics
on:
  workflow_dispatch:
  push:
    branches: [master, main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate Chess metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.chess.svg
          token: NOT_NEEDED
          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_platform: lichess.org
