name: Github Metrics

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 AM IST (6:30 PM UTC) every day
    - cron: "30 18 * * *"
  push:
    branches: [master, main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.*
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "chore: Update ${filename}"
          base: activity, community, repositories, metadata
          base_skip: header
          plugin_introduction: no
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_lines_sections: base
          plugin_lines_repositories_limit: 4
          plugin_lines_history_limit: 1
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          config_order: introduction, base.activity+community, base.repositories, lines, wakatime, topics, achievements

  codeforces-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Fetch Codeforces Stats
        env:
          CF_HANDLE: ${{ secrets.CF_HANDLE }}  # Add your Codeforces handle as a secret
        run: |
          python fetch_codeforces_stats.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update Codeforces stats'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
